# Generated by Django 4.2 on 2024-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('ph_num', models.IntegerField()),
                ('education', models.TextField(max_length=2000)),
                ('degree', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('experience', models.TextField(max_length=2000)),
                ('hobbies', models.TextField(max_length=2000)),
            ],
        ),
    ]
