# Generated by Django 4.2 on 2024-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_alter_profile_hobbies_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ph_num',
            field=models.CharField(max_length=12),
        ),
    ]
